# -*- coding: utf-8 -*-
"""NavitaHooda_week2assignment_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1Jx-GzfEs5xGJIeDE5kLPUr3rx3mszc
"""

# IMPORTING LIBRARIES

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.preprocessing import LabelEncoder

# QUES 1: Load the dataset and display the first five records.

#loading...
df = pd.read_csv('Dataset 2.csv')

#displaying 5 rows...
df.head()

# QUES 2: Determine the number of rows and columns in the dataset.

#it will give outpur in (rows, columns)
print('Shapes:', df.shape)

#QUES 3: Display all column names.

print('columns:\n')
print(df.columns)

#QUES 4: Identify numerical and categorical features.

#printing data types
print('Data types:', df.dtypes)

#categorizing
numerical_features = ['Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks', 'MonthlySpend']
categorial_features = ['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed']

print('\n\n')
print('Numerical features are:', numerical_features)
print('Categorial features are:', categorial_features)

#QUES 5: Check whether the dataset contains missing values.

print("Missing values in each column are")
print(df.isnull().sum())

#QUES 6: Calculate the average age of users.

avg_age = df['Age'].mean()
print('The average age is:', avg_age)

#QUES 7: Determine the average watch hours per week.

avg_watching_hrs = df['WatchHoursPerWeek'].mean()
print('The average watch hours per week is:', avg_watching_hrs)

#QUES 8: Find the average monthly spending of users.

avg_monthly_spend = df['MonthlySpend'].mean()
print('The average monthly spend is:', avg_monthly_spend)

#QUES 9: Count the number of users in each subscription category

subscription_counts = df['SubscriptionType'].value_counts()
print(subscription_counts)

#QUES 10: Determine the percentage of users who renewed their subscriptions

renewal_percentages = df['SubscriptionRenewed'].value_counts(normalize=True) * 100
print(renewal_percentages)

#QUES 11: Convert categorical features into numerical form.

le = LabelEncoder()

for col in categorial_features:
  df[col] = le.fit_transform(df[col])

#display first 5 records to verify the conversion
df.head()

# QUES 12: Define the feature set (X) and target variable (y) for subscription renewal prediction

# Drop the target column and the unique identifier for features
X = df.drop(columns=['UserID', 'SubscriptionRenewed'])

# Assign the target column to y
y = df['SubscriptionRenewed']

# Display the shapes to verify
print("Features shape (X):", X.shape)
print("Target shape (y):", y.shape)

# QUES 13: Split the dataset into training and testing sets.

# Splitting the data (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting sets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# QUES 14: Train a Decision Tree model to predict whether a user will renew their subscription.

# 1. Initialize the Decision Tree Classifier
dt_model = DecisionTreeClassifier(random_state=42)

# 2. Train (fit) the model on the training data
dt_model.fit(X_train, y_train)

# 3. Predict the labels for the test set
dt_predictions = dt_model.predict(X_test)

print("Decision Tree model training complete and predictions generated!")

# QUES 15: Evaluate the model using accuracy.

dt_accuracy = accuracy_score(y_test, dt_predictions)

print(f"Decision Tree Model Accuracy: {dt_accuracy * 100:.2f}%")

# QUES 16: Generate and interpret the confusion matrix.

# Generate the confusion matrix
dt_cm = confusion_matrix(y_test, dt_predictions)

# Print the raw matrix
print("Confusion Matrix:")
print(dt_cm)

# Print a breakdown for easier interpretation
tn, fp, fn, tp = dt_cm.ravel()
print(f"\nBreakdown:")
print(f"True Negatives (Predicted 'No', Actual 'No'): {tn}")
print(f"False Positives (Predicted 'Yes', Actual 'No'): {fp}")
print(f"False Negatives (Predicted 'No', Actual 'Yes'): {fn}")
print(f"True Positives (Predicted 'Yes', Actual 'Yes'): {tp}")

# QUES 17: Train a KNN classifier with K = 5.

# Initialize the KNN Classifier with n_neighbors=5
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train (fit) the model on your training data
knn_model.fit(X_train, y_train)

# Predict the labels for the test set
knn_predictions = knn_model.predict(X_test)

print("KNN classifier (K=5) training complete and predictions generated!")

# QUES 18: Compare the accuracy of KNN with the Decision Tree model.

# Calculate the accuracy score for the KNN model
knn_accuracy = accuracy_score(y_test, knn_predictions)

# Print both accuracy scores for comparison
print(f"Decision Tree Model Accuracy: {dt_accuracy * 100:.2f}%")
print(f"KNN Model Accuracy:           {knn_accuracy * 100:.2f}%\n")

# Automatically determine and print which model performed better
if knn_accuracy > dt_accuracy:
    difference = (knn_accuracy - dt_accuracy) * 100
    print(f"Conclusion: The KNN model performed better than the Decision Tree model by {difference:.2f}%.")
elif dt_accuracy > knn_accuracy:
    difference = (dt_accuracy - knn_accuracy) * 100
    print(f"Conclusion: The Decision Tree model performed better than the KNN model by {difference:.2f}%.")
else:
    print("Conclusion: Both models performed equally well with the exact same accuracy.")

# QUES 19: Train a Linear Regression model to predict monthly spending.

# Define features (X_reg) and target (y_reg) for the regression task
# drop 'MonthlySpend' (target) and 'UserID' (identifier)
X_reg = df.drop(columns=['UserID', 'MonthlySpend'])
y_reg = df['MonthlySpend']

# Split the data into training and testing sets (80% train, 20% test)
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Initialize the Linear Regression model
lr_model = LinearRegression()

# Train (fit) the model on the regression training data
lr_model.fit(X_train_reg, y_train_reg)

print("Linear Regression model training complete!")

# QUES 20: Predict the monthly spending for a new user and interpret the result.

# Create a dummy record for a new user matching the feature structure exactly
new_user_data = {
    'Age': [30],
    'Gender': [0],
    'SubscriptionType': [1],
    'WatchHoursPerWeek': [25],
    'DevicesUsed': [3],
    'FavoriteGenre': [3],
    'AdClicks': [12],
    'SubscriptionRenewed': [1]
}

# Convert the dictionary into a DataFrame with the exact same column order as X_reg
new_user_df = pd.DataFrame(new_user_data, columns=X_reg.columns)

# Predict the monthly spending
predicted_spend = lr_model.predict(new_user_df)[0]

# Display the result
print(f"Predicted Monthly Spending for the new user: ${predicted_spend:.2f}")

#business reflection question

# QUES 1: Which factors appear to influence subscription renewal the most?


#Based on the machine learning models and dataset analysis, the factors that likely influence subscription renewal the most include:
#Watch Hours Per Week, Subscription Type, Monthly Spend vs. Engagement Balance, Ad Clicks

# QUES 2: Why is subscription renewal a classification problem?

#Subscription renewal is a classification problem because the target outcome we are trying to predict is categorical and discrete, rather than a continuous number.

# QUES 3: Why is monthly spending a regression problem?

#Monthly spending is a regression problem because the target outcome we are trying to predict is a continuous numerical value, rather than a fixed category or label.

# QUES 4: Which algorithm performed better for renewal prediction?

#The K-Nearest Neighbors (KNN) algorithm performed better for renewal prediction compared to the Decision Tree model.
#KNN Accuracy: 63.33%
#Decision Tree Accuracy: 56.00%

# QUES 5: How could the platform use these predictions to improve customer retention?

#The platform can turn these classification and regression predictions into actionable business strategies in several ways:
#Proactive Retention Campaigns
#Personalized Engagement Boosts
#Optimized Dynamic Pricing
#Feature Incentivization